### PR TITLE
Adding some 'Aw Yiss' goodness

### PR DESCRIPTION
**Pull request by trlinkin**

### CODE REVIEW

**Comment by dferramosi** [comment]
you need to add that script to the external scripts file or it wont load

**Comment by trlinkin** [comment]
I thought hubot automatically loaded everything from the scripts dir...?

**Comment by dferramosi** [comment]
hmm... let's see

**Comment by dferramosi** [comment]
You were correct! (merged as it wouldn't have broken anything just potentially not loaded)

**Pull request merged**
